const categories = [
  { name: "Spices & Masala", emoji: "🌶️", items: "Arabian Mandi Masala, Pepper Tikka Masala Mix, Oregano, Al Faham Masala, Peri Peri Masala, Kasturi Methi, Chilli Flakes, Bengaluru White Kabab Masala, Bengaluru Green Kabab Masala, Bengaluru Red Kabab Masala, Sari Dhaniya, Tikhala Chilli Powder, MTR Chilli Powder, Kwality Chilli Powder, Byadgi Chilli Powder, MTR Coriander Powder, Turmeric Powder Kwality, MTR Turmeric Powder, Himalayan Pink Salt, Himalayan Pink Rock Salt Crystal, Barik Salt Pink, Pepper Chudve, Methi, Zeera, Rayaa, Teju Chicken Masala and Fry, Kwality Super Garam Masala, Teju Chicken Kabab Powder, Teju Mutton Masala and Fry, Black Pepper Powder, Jeera Powder, White Pepper Powder, Chicken Curry Masala, Salt, Fish Fry Masala, Chicken Kabab Masala, MTR Puliyogare Powder, MTR Rasam Powder, MTR Chilli Powder, Yippee Magic Masala, Black Salt, Dry Ginger Powder, Dry Mango Powder, Jaljeera Powder, Kitchen King Masala, Chhole Masala, Chaat Masala, Kashmiri Chilli Powder, Chicken Masala, Garam Masala, Chicken Biryani Masala, Jeera Powder, Meat Masala, Sabji Masala, Pani Puri Masala, Pav Bhaji Masala, Shahi Biryani Masala, Kabsa Mandi Masala, Salt, Rock Salt, Black Salt, Pepper, Pepper Powder, Mustard Seeds, Fenugreek Seeds, Coriander Seeds, Cumin Seeds, Fennel Seeds, Ajwain, Hing, Turmeric Powder, Chilli Powder, Coriander Powder, Garam Masala, Chicken Masala, Mutton Masala, Biryani Masala, Kitchen King Masala, Chhole Masala, Chaat Masala, Pav Bhaji Masala, Pani Puri Masala, Sabji Masala, Bleaching Powder, Salt Biscuit, Bleaching Powder, Pepper Cashew, Salted Pistachios, Pepper Cashew, Salted Pista, Saffola Masala Oats Veggie Twist, Colgate Active Salt" },
  { name: "Pasta, Noodles & Vermicelli", emoji: "🍝", items: "Noodles, MTR Saviyan Vermicelli, Bambino Bell Vermicelli, DSP Vermicelli, Anil Roasted Short Vermicelli, Chabil Saviyan, Albo Pasta, Medium Chudve, Mota Chudve, Top Ramen Fiery Chilli, Yippee Noodles, Yippee Noodles, Pasta, Macaroni, Spaghetti, Noodles, Instant Noodles, Cup Noodles, Semiya, Vermicelli, Noodle Soup" },
  { name: "Personal Care & Hygiene", emoji: "🧼", items: "Ginger and Garlic Paste, Castor Oil, Gulab Jal, Rose Water, Gulabari, Vatika Coconut Oil, Dabur Amla Hair Oil, Parachute Aloe Vera Coconut Oil, Parachute Coconut Oil, Dabur Anmol Gold Coconut Oil, Bajaj Gold Coconut Oil, Pepsodent Paste, Colgate Maxfresh, Colgate Paste, Closeup Paste, Meswak Paste, Dabur Red Paste, Neem Active Paste, Colgate Cibaca, Sensodyne Repair and Protect, Sensodyne Fresh Mint, Anchor Clove Power, Farooky Tooth Powder, Vatika Shampoo, Karthika Shampoo, Chik Shampoo, Sunsilk Shampoo, Indulekha Shampoo, Head and Shoulders, Vaseline, Ponds Cream, Glow and Lovely, Electral, Dettol Soap, Margo Soap, Chandrika Soap, Medimix Soap, Mysore Sandal Soap, Lux Soap, Dove Soap, Pears Soap, Lifebuoy Soap, Santoor Soap, Wheel Soap, Monkey Soap, Ganesh Soap, Toothpaste, Toothbrush, Mouthwash, Face Wash, Face Cream, Body Lotion, Hair Oil, Shampoo, Conditioner, Hair Serum, Soap, Bath Soap, Hand Wash, Sanitizer, Shaving Cream, Shaving Razor, Talcum Powder, Deodorant, Perfume, Comb, Fabric Conditioner" },
  { name: "Tea, Coffee & Hot Beverages", emoji: "☕", items: "Shalimar Gold, Red Label, 3 Roses, Natural Care, Green Tea, Taj Mahal, BRU Green Label, Taaza Tea Powder, Vasavi Coffee, Aman Leaf Tea, Megha Gold Tea Powder, Kohinoor Tea, Malabar Tea, Kanan Devan Strong, Hotel Blend Red Label, Hotel Blend 3 Roses, KT Special Tea, Silver Supreme Tea Dust, Bournvita, Boost, Junior Horlicks, Horlicks Womens Plus, Horlicks, Talbina, Tea Powder, Coffee Powder, Instant Coffee, Filter Coffee, Green Tea, Lemon Tea, Ginger Tea, Elaichi Tea, Boost, Bournvita, Horlicks, Junior Horlicks, Women Horlicks, Protein Powder, Cold Coffee, Talbina" },
  { name: "Cooking Oils & Ghee", emoji: "🛢️", items: "Freedom Kachi Ghani Mustard Oil, Fortune Pure Mustard Oil, Tunza Pure Olive Oil, KLF Coconut Oil, Cooking Oil, Coconut Oil, Mustard Oil, Sunflower Oil, Groundnut Oil, Palm Oil, Olive Oil" },
  { name: "Sauces, Pickles & Condiments", emoji: "🥫", items: "Kissan Mixed Fruit Jam, Lime Pickle, Mango Pickle, Mixed Vegetable Pickle, Mayonnaise, Disono Honey, Dabur Honey, Chikmagalur Honey, Green Chilli Sauce, Red Chilli Sauce, Tomato Sauce, Soya Sauce, Chilli Vinegar, Maggi Chicken Stock, Apple Cider Vinegar, Cooking Vinegar, Maggi Stock, Ketchup, Tomato Ketchup, Chilli Ketchup, Mayonnaise, Eggless Mayo, Garlic Mayo, Tandoori Mayo, Honey, Jam, Marmalade, Syrup, Maple Syrup, Strawberry Syrup, Vinegar, Apple Vinegar, White Vinegar, Soya Sauce, Dark Soya Sauce, Light Soya Sauce, Chilli Sauce, Green Chilli Sauce, Red Chilli Sauce, Schezwan Sauce, Pickle, Mango Pickle, Lime Pickle, Mixed Pickle, Garlic Pickle, Ginger Pickle, Green Chilli Pickle, Non Veg Pickle, Fish Pickle, Chicken Pickle, Jelly Crystals, Red Chilli Sauce, Chilli Vinegar, Red Chilli Sauce" },
  { name: "Dairy Products", emoji: "🥛", items: "Saffola Peanut Butter, Amulya Dairy Whitener, Amul Fresh Cream, Milky Mist Sweetened Condensed Milk, Sri Krishna Ghee, Swastik Ghee, GRB Ghee, Nandini Ghee, Ruchi No1 Vanaspati, FR Badam Pista Milk Mix Essence, FR Rose Milk Mix Essence, Badam Milk Mix, Dairy Milk Chocolate, Eclairs Royale Milky, Milk Cheese, Falooda Mix Butterscotch, Milk Jelly, Milk, Cheese, Falooda Butterscotch, Butter, Cheese Slice, Paneer, Curd, Milk Packet, Buttermilk, Lassi, Flavoured Milk, Cheese Spread, Peanut Butter, Kanan Devan Classic, India Gate Classic Chawal" },
  { name: "Biscuits, Snacks & Namkeen", emoji: "🍪", items: "Choco Flakes, Gulshan Seviyan, Kunafa Seviyan, Marie Light Biscuit, Parle G, Pop N Hop, Knackjack Biscuit, Aloo Bhujia, Bourbon Biscuit, Britannia Family Pack, Nutri Choice Biscuit, Tedhe Medhe, Marie Light, Parle G, Pop N Hop, Kurkure, Aloo Bhujia, Bourbon, Britannia Biscuit, Oreo, Nutri Choice, Biscuit Pack, Cream Biscuit, Glucose Biscuit, Digestive Biscuit, Cracker Biscuit, Namkeen, Mixture, Sev, Bhujia, Chips, Potato Chips, Banana Chips, Nachos, Popcorn, Sweet Corn, Sweet Corn Soup" },
  { name: "Breakfast & Health Foods", emoji: "🥣", items: "Crunchy Muesli Fruit Nut and Seeds, Mother Root, Saffola Oats Soft and Creamy, Makhana, Emle, Makhana, Oats, Cornflakes, Chocos, Muesli, Poha" },
  { name: "Soft Drinks, Juices & Beverages", emoji: "🥤", items: "Tang Mango, Tang Orange, Mala Mango Crush, Mala Apple Crush, Mala Guava Crush, Mala Mosambi Crush, Rooh Afza, Blue Curacao, Mojito Syrup, Ginger Lime Syrup, Apple Crush, Chikoo Crush, Mosambi Crush, Guava Crush, Mango Crush, Rooh Afza, Blue Curacao Syrup, Mojito, Ginger Lime, Coca Cola, Pepsi, Sprite, Fanta, Limca, Maaza, Slice, Appy, Fruity, Real Juice, Tropicana Juice, Mixed Fruit Juice, Orange Juice, Apple Juice, Mango Juice, Guava Juice, Pineapple Juice, Mosambi Juice, Lemon Juice, Soda, Club Soda, Tonic Water, Chocolate Spread, Chocolate Syrup, Baking Soda, Eclairs Chocolate, Happy Happy Biscuit, Chocolate Biscuit, Chocolate Ice Cream, Eclairs Chocolate, Happy Happy, Swastiks Fantastic Non-stick Vermicelli, Baking Soda, Cold Coffee" },
  { name: "Bread, Bakery & Sweets", emoji: "🍞", items: "MTR Gulab Jamun, Swastiks Gulab Jamun Mix, Kwality Gulab Jamun, MTR Rava Idli, Pancake Mix, Gulkand, Eclairs Royale, Pancake Mix, Malai Peda, Gulkand, Bread, Brown Bread, White Bread, Sandwich Bread, Burger Bun, Pizza Base, Pav Bread, Rusk, Toast, Cake, Pastry, Muffin, Donut, Cake Mix" },
  { name: "Baking Ingredients & Essences", emoji: "🧁", items: "Coconut Desiccated Coconut Powder, FR Biryani Essence, FR Vanilla Essence, Pineapple Essence, Diamond Food Colour Orange Red, Sago Dana Mota, Sago Dana Barik, Agar Agar, Dry Yeast, Cocoa Powder, Baking Powder, Baking Powder, Yeast, Cocoa Powder, Vanilla Essence, Strawberry Essence, Pineapple Essence, Food Colour, Gelatine, Agar Agar" },
  { name: "Pulses & Legumes", emoji: "🫘", items: "Fortune Soya Chunks, Lal Lobia, White Lobia, Soya Beans, Green Batani, Kabuli Channa, Kulthi, Moong, Channa, Masoor Dal, Moong Dal, Mashki Dal, Toor Dal" },
  { name: "Ready Mixes, Soups & Convenience Foods", emoji: "🍲", items: "Bru Ram Appalam, Urad Papad Appalam, Boti Papad, Fryums Pani Puri Papad, Custard Powder, Rice Papad, Rice Papad, Papad, Fryums, Appalam, Sandige, Vadi, Ready Mix, Idli Mix, Dosa Mix, Upma Mix, Pongal Mix, Instant Soup, Tomato Soup, Hot and Sour Soup, Manchow Soup, Clear Soup, Chicken Soup, Veg Soup, Cup Soup, Custard Mix, Pudding Mix, Brownie Mix" },
  { name: "Flours, Grains & Staples", emoji: "🌾", items: "Fortune Chakki Fresh Atta, Ragi Flour, Vijay Gold Idli Rava, Sundare Swaad Chakki Atta, Ganesh Maida Flour, Naivedyam Jaggery, KBR Jaggery Powder, Mistri Red, Mistri White, Ganesh Gram Flour, Corn Flour, Sooji, Mot, Bansi Kesari Rava, Gud, Fortune Chiroti Rava, Parrys White Label Sugar, Bangalore Rava, Maida, Atta, Sugar, Ashirvaad Atta, Potato, Maharaja Atta, Atta, Potato, Rava, Suji, Wheat Flour, Maida, Besan, Corn Flour, Multigrain Flour, Ragi Flour, Bajra Flour, Jowar Flour, Soya Flour, Sugar, Brown Sugar, Jaggery, Powder Sugar, Jeera, Jelly, Jelly, Oil, Tang" },
  { name: "Rice & Rice Products", emoji: "🍚", items: "Vijay Gold Rice Flour, Barli Chaval, India Gate Rice, Bullet Chawal, Rice, Basmati Rice, Raw Rice, Boiled Rice, Idli Rice, Rice Flour" },
  { name: "Dry Fruits & Nuts", emoji: "🥜", items: "Palleke Dane, Putane, Sukka Gokra, Badam, Kiwi, Amla, Watermelon Seeds, Mixed Nuts, Walnuts, Black Raisins, Roasted Almonds, Cashew, Dates, Anjeer, Taj Mishri, Badam, Banana, Kiwi Fruit, Amla, Mixed Nuts, Walnuts, Black Raisins Seedless, Dry Fruits, Kaju, Dates, Anjeer, Mishri" },
  { name: "Household Cleaning & Laundry", emoji: "🧹", items: "Surf Excel, Vim Bar, Nimyle, Domex, Harpic, Odonil Air Freshener, Comfort, Garbage Bags, Surf Powder, Mysore Powder, Henko, Ghadi, More Light, Nirma, Tide, Steel Scrubber, Steel Sponge, Surf Excel Matic, Surf Front Load, Surf Quick Wash, Surf Easy Wash, Ujala, Rin, Vim Liquid, Exo Dishwash, Dishwash Bar, Glass Cleaner, Floor Cleaner, Toilet Cleaner, Harpic Power, Domex Thick, Odonil Block, Air Freshener Spray, Garbage Cover, Plastic Cover, Carry Bags, Match Box, Candle, Detergent Powder, Detergent Liquid, Dishwash Liquid, Dishwash Bar, Floor Cleaner, Toilet Cleaner, Glass Cleaner, Phenyl, Scrubber, Sponge, Mop, Broom, Bucket, Mug, Dustbin, Garbage Bag, Cloth Clip, Cleaning Cloth, Odonil, Toothpicks, Spring Pasta, Energy Drink, Soft Drinks, Energy Drink Can, Spring Roll, Tooth Pick" },
  { name: "Agarbathi, Puja & Home Essentials", emoji: "🪔", items: "Mangaldeep Anushri, Cycle Brand, Mysore Sandal Agarbathi, Mangaldeep Sandal, Mangaldeep Magical Mogra, Mansarovar, Kesar Chandan Agarbathi, Wild Musk Agarbathi, Mangaldeep Radiant Amber, Mangaldeep Royal Rose, Zed Black Pure Bliss, Mangaldeep Lavish Lavender, Mangaldeep Blissful Bouquet, Mangaldeep Blue Lagoon, Mangaldeep Majestic Oudh, Agarbathi, Mangaldeep Agarbathi, Cycle Agarbathi, Zed Black Agarbathi, Incense Sticks" },
  { name: "Frozen Foods & Ice Cream", emoji: "🍦", items: "Ice Cream Mix, Falooda Mix Pineapple, Ice Cream Mix, Falooda Pineapple, Falooda Strawberry, Falooda Kesar, Falooda Pista, Falooda Mango, Ice Cream, Vanilla Ice Cream, Strawberry Ice Cream, Kulfi, Falooda, Frozen Peas, Frozen Corn, Frozen Veg Mix, Frozen Chicken, Frozen Fish, Frozen Snacks, Nuggets, Fries, Cutlet, Samosa, Momos, Ice Cream Cone, Ice Cream Stick, Ice Cream Family Pack, Kulfi Stick, Falooda Mix" }
];

const slugify = (text) => text.toLowerCase().replace(/ & /g, '-').replace(/, /g, '-').replace(/ /g, '-').replace(/[^\w-]+/g, '');

const allProducts = [];
const allCategories = [];

categories.forEach((cat) => {
  const catSlug = slugify(cat.name);
  const items = cat.items.split(',').map(i => i.trim()).filter(i => i);
  
  allCategories.push({
    name: cat.name,
    slug: catSlug,
    emoji: cat.emoji,
    itemCount: items.length
  });

  items.forEach((item) => {
    allProducts.push({
      name: item,
      category: cat.name,
      categorySlug: catSlug,
      price: 0,
      unit: "",
      imageUrl: "",
      inStock: true
    });
  });
});

const fs = require('fs');
fs.writeFileSync('data/products.json', JSON.stringify(allProducts, null, 2));
fs.writeFileSync('data/categories.json', JSON.stringify(allCategories, null, 2));

console.log(`Generated ${allProducts.length} products in ${allCategories.length} categories.`);
