name: Build Admin APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          bubblewrap init --manifest=https://alfajr-yr3u.vercel.app/manifest-admin.json --directory=./admin-apk --confirmResign=true
          cd admin-apk
          bubblewrap build --skip-signing
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Alfajr-Admin-APK
          path: ./admin-apk/*.apk
